sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ademolamacgregor/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ademolamacgregor/docker-react npm run test
